### PR TITLE
Added taxoman custom facets to edx-search

### PR DESCRIPTION
**Pull request by johnbaldwin**
I manually tested taxoman via the UI in a staging server and this works as I expect it.

First, I created a downstream branch (appsembler/ficus/develop) from edx/edx-search's release 0.1.2, which is the tag specified for edx-platform `open-release/ficus.master`

Then I created this branch off of our `appsembler/ficus/develop` branch

See trello card: https://trello.com/c/dkBRwmmO/223-5-taxoman-update-edx-search-for-ficus-taxoman

To note: This is a schedule driven port from our update to edx-search for Dogwood. I didn't add to the unit tests. We'll want to abstract this (for general facet additions) and add to the unit tests before we submit a PR to upstream

### CODE REVIEW

**Comment by johnbaldwin** [comment]
[(5) Taxoman: Update edx-search for Ficus Taxoman](https://trello.com/c/dkBRwmmO/223-5-taxoman-update-edx-search-for-ficus-taxoman)

**Comment by OmarIthawi** [comment]
I've taken a look, it looks cryptic to me @johnbaldwin because I don't have enough knowledge about `edx-search`. So, your best shot for taking a good review is to submit this upstream and hope that someone will review it in a timely manner.

**Comment by johnbaldwin** [comment]
@OmarIthawi Thanks for taking a look. I really want to make this upstream ready before I do an upstream PR. I might have some time at the end of this sprint to work on that a bit

**Comment by johnbaldwin** [comment]
@OmarIthawi To note, I created a couple of issues in this repo to make this upstreamable

**Comment by johnbaldwin** [comment]
[(8) Taxoman: update Ficus edx-platform common branch](https://trello.com/c/2DRq8tyX/212-8-taxoman-update-ficus-edx-platform-common-branch)

**Comment by johnbaldwin** [comment]
[(1) Metacard: Upgrade Taxoman for Ficus for Metalogix](https://trello.com/c/5hfGwWUa/201-1-metacard-upgrade-taxoman-for-ficus-for-metalogix)

**Review by bryanlandia — APPROVED** [review]
This is a bit of a shallow review since I'm not that experienced with edx-search, either.  Everything here looks good to me, though.  Maybe just squash the Jan 16 and Jan 17 commits.

**Comment by johnbaldwin** [comment]
Rebased and squashed the Jan 16 & 17 commits. Closing PR and deleting branch

**Pull request closed without merging**
